// Display-only Chinese city names. Sources and licenses: docs/data/CITY_NAMES.md.
// Values contain the display name followed by searchable Chinese variants.
export const CITY_NAMES_ZH = {
  "AE": {
    "Dubai": ["杜拜", "迪拜"],
  },
  "AR": {
    "Buenos Aires": ["布宜诺斯艾利斯"],
    "Córdoba": ["科尔多瓦"],
    "La Plata": ["拉普拉塔"],
    "Mendoza": ["门多萨"],
    "Salta": ["萨尔塔"],
  },
  "AT": {
    "Eisenstadt": ["艾森斯塔特"],
    "Graz": ["格拉茨"],
    "Linz": ["林茨"],
    "Vienna": ["维也纳", "維也納"],
  },
  "AU": {
    "Brisbane City": ["布里斯班"],
    "Canberra": ["堪培拉"],
    "Geelong": ["吉朗"],
    "Maryborough": ["马里伯勒"],
    "Newcastle": ["纽卡斯尔"],
    "North Sydney": ["北悉尼"],
    "Perth": ["珀斯"],
    "Redfern": ["红坊"],
    "South Brisbane": ["南布里斯本"],
    "St Kilda": ["圣基尔达"],
    "Surfers Paradise": ["冲浪者天堂"],
    "Townsville": ["汤斯维尔"],
    "Williamstown": ["威廉斯顿", "威廉斯頓"],
  },
  "BD": {
    "Dhaka": ["达卡"],
  },
  "BE": {
    "Antwerp": ["安特卫普"],
    "Bruges": ["布鲁日", "布吕赫"],
    "Ghent": ["根特"],
    "Liège": ["列日"],
    "Mechelen": ["梅赫伦"],
  },
  "BG": {
    "Ruse": ["鲁塞"],
    "Sofia": ["索菲亚", "索菲亞"],
  },
  "BO": {
    "Cochabamba": ["科恰班巴"],
    "Santa Cruz de la Sierra": ["圣克鲁斯-德拉谢拉"],
  },
  "BR": {
    "Belo Horizonte": ["贝洛奥里藏特", "貝洛奥里藏特"],
    "Campinas": ["坎皮纳斯"],
    "Curitiba": ["库里蒂巴", "庫里奇巴", "库里奇巴"],
    "Guarulhos": ["瓜鲁柳斯"],
    "Niterói": ["尼泰罗伊"],
    "Rio de Janeiro": ["里约热内卢"],
    "Salvador": ["萨尔瓦多"],
    "São Paulo": ["圣保罗"],
  },
  "BY": {
    "Minsk": ["明斯克", "明斯克市"],
    "Mogilev": ["莫吉廖夫"],
  },
  "CA": {
    "Calgary": ["卡尔加里"],
    "Edmonton": ["埃德蒙顿"],
    "Montreal": ["蒙特利尔"],
    "Ottawa": ["渥太华", "渥太華"],
    "Quebec City": ["魁北克市"],
    "Toronto": ["多伦多"],
    "Vancouver": ["温哥华", "溫哥華"],
    "Victoria": ["维多利亚", "維多利亞"],
    "Winnipeg": ["温尼伯"],
  },
  "CH": {
    "Basel": ["巴塞尔"],
    "Bern": ["伯尔尼", "伯恩"],
    "Geneva": ["日内瓦"],
    "Mendrisio": ["门德里西奥", "門德里西奧"],
    "Zürich": ["苏黎世"],
  },
  "CL": {
    "Concepción": ["康塞普西翁"],
    "Coquimbo": ["科金博"],
    "La Serena": ["拉塞雷纳"],
    "Providencia": ["普罗维登西亚"],
    "Valparaíso": ["瓦尔帕莱索"],
    "Viña del Mar": ["比尼亚德尔马"],
  },
  "CN": {
    "Beijing": ["北京市", "北京"],
    "Chengdu": ["成都市", "成都", "天府"],
    "Chongqing": ["重庆市", "重庆"],
    "Dalian": ["大连市", "大连"],
    "Foshan": ["佛山", "佛山市"],
    "Fuzhou": ["福州市"],
    "Guangzhou": ["广州市", "广州"],
    "Hangzhou": ["杭州市", "杭州"],
    "Jinan": ["济南市", "济南"],
    "Nanjing": ["南京市", "南京"],
    "Shanghai": ["上海市", "上海", "中国上海"],
    "Shenzhen": ["深圳市", "深圳"],
    "Suzhou": ["苏州市", "苏州"],
    "Wuxi": ["无锡市", "无锡"],
    "Xiamen": ["厦门市"],
  },
  "CO": {
    "Armenia": ["亚美尼亚城"],
    "Bogotá": ["波哥大"],
    "Bucaramanga": ["布卡拉曼加"],
    "Cali": ["卡利"],
    "Cartagena": ["卡塔赫纳"],
    "Guatapé": ["瓜塔佩"],
    "Manizales": ["马尼萨莱斯", "馬尼薩萊斯"],
    "Medellín": ["麦德林"],
    "Pereira": ["佩雷拉"],
    "Popayán": ["波帕扬"],
    "San Andrés": ["圣安德烈斯"],
    "Tunja": ["通哈"],
  },
  "CZ": {
    "Brno": ["布尔诺", "布爾諾"],
    "Ostrava": ["俄斯特拉发", "俄斯特拉發", "奥斯特拉瓦"],
    "Prague": ["布拉格"],
  },
  "DE": {
    "Aachen": ["亚琛"],
    "Aschaffenburg": ["阿沙芬堡"],
    "Bad Buchau": ["巴特布豪"],
    "Berlin": ["柏林"],
    "Bochum": ["波鸿"],
    "Bonn": ["波恩"],
    "Bremen": ["不来梅"],
    "Chemnitz": ["开姆尼茨"],
    "Cologne": ["科隆"],
    "Dessau-Roßlau": ["德绍-罗斯劳", "德绍"],
    "Dortmund": ["多特蒙德"],
    "Dresden": ["德累斯顿"],
    "Düsseldorf": ["杜塞尔多夫"],
    "Erfurt": ["埃尔福特"],
    "Frankfurt": ["美因河畔法兰克福", "法兰克福", "法蘭克福"],
    "Freiburg im Breisgau": ["弗赖堡", "弗莱堡"],
    "Halle (Saale)": ["萨勒河畔哈雷"],
    "Hamburg": ["汉堡", "汉堡市"],
    "Hanover": ["汉诺威地区", "汉诺威"],
    "Hildesheim": ["希尔德斯海姆"],
    "Karlsruhe": ["卡尔斯鲁厄"],
    "Kiel": ["基尔"],
    "Leipzig": ["莱比锡"],
    "Lübeck": ["吕贝克"],
    "Lüneburg": ["吕讷堡", "吕内堡"],
    "Magdeburg": ["马格德堡"],
    "Mannheim": ["曼海姆"],
    "Munich": ["慕尼黑"],
    "Nuremberg": ["纽伦堡"],
    "Oranienbaum-Wörlitz": ["奥拉宁鲍姆-沃利茨"],
    "Potsdam": ["波茨坦"],
    "Regensburg": ["雷根斯堡"],
    "Rotenburg an der Fulda": ["富尔达河畔罗滕堡"],
    "Schwerin": ["什未林"],
    "Stuttgart": ["斯图加特"],
    "Wiesbaden": ["威斯巴登"],
    "Würzburg": ["维尔茨堡"],
  },
  "DK": {
    "Copenhagen": ["哥本哈根"],
  },
  "DO": {
    "Santo Domingo": ["圣多明哥", "聖多明哥"],
  },
  "EC": {
    "Ambato": ["安巴托"],
    "Manta": ["曼塔"],
    "Portoviejo": ["波托维耶霍", "波托維耶霍"],
    "Quito": ["基多"],
  },
  "EE": {
    "Tallinn": ["塔林"],
  },
  "ES": {
    "Alcala de Henares": ["埃纳雷斯堡"],
    "Barcelona": ["巴塞罗那"],
    "Burgos": ["布尔戈斯"],
    "Córdoba": ["科尔多瓦", "科爾多瓦"],
    "Granada": ["格拉纳达", "格林纳达"],
    "Leioa": ["莱奥阿"],
    "Madrid": ["马德里", "馬德里"],
    "Palma": ["帕尔马"],
    "Sabadell": ["萨瓦德尔"],
    "Tarragona": ["塔拉戈纳"],
    "Valencia": ["瓦伦西亚", "巴倫西亞", "巴伦西亚"],
  },
  "FI": {
    "Espoo": ["埃斯波"],
    "Helsinki": ["赫尔辛基"],
    "Lahti": ["拉赫蒂"],
    "Oulu": ["奥卢"],
    "Turku": ["图尔库"],
  },
  "FR": {
    "Le Havre": ["勒阿弗尔"],
    "Lille": ["里尔"],
    "Lyon": ["里昂"],
    "Marseille": ["马赛"],
    "Montpellier": ["蒙彼利埃"],
    "Nantes": ["南特"],
    "Paris": ["巴黎"],
    "Reims": ["兰斯"],
    "Toulouse": ["图卢兹", "圖盧茲"],
  },
  "GB": {
    "Aberdeen": ["阿伯丁"],
    "Belfast": ["贝尔法斯特", "貝爾法斯特"],
    "Birmingham": ["伯明翰", "伯明翰市"],
    "Brighton and Hove": ["布来顿和荷甫"],
    "Bristol": ["布里斯托尔"],
    "Cambridge": ["剑桥", "劍橋"],
    "Canterbury": ["坎特伯雷"],
    "Cardiff": ["加的夫"],
    "Coventry": ["考文垂"],
    "Edinburgh": ["爱丁堡"],
    "Glasgow": ["格拉斯哥"],
    "Leeds": ["利兹"],
    "London": ["伦敦"],
    "Maidstone": ["梅德斯通"],
    "Oban": ["奥本", "奧本"],
    "Southampton": ["南安普敦"],
  },
  "GE": {
    "Tbilisi": ["第比利斯"],
  },
  "GI": {
    "Gibraltar GX11 1AA": ["直布罗陀"],
  },
  "GR": {
    "Athens": ["雅典"],
  },
  "HK": {
    "Hong Kong": ["香港"],
  },
  "HN": {
    "San Pedro Sula": ["圣佩德罗苏拉"],
  },
  "HR": {
    "Zagreb": ["萨格勒布"],
  },
  "HU": {
    "Budapest": ["布达佩斯"],
    "Keszthely": ["凯斯特海伊", "凱斯特海伊"],
    "Miskolc": ["米什科尔茨"],
  },
  "ID": {
    "Bandung": ["万隆", "萬隆"],
    "Kuta": ["库塔", "庫塔"],
    "Surabaya": ["泗水"],
    "West Jakarta": ["西雅加达行政市"],
    "Yogyakarta": ["日惹"],
  },
  "IE": {
    "Dublin": ["都柏林"],
  },
  "IL": {
    "Tel Aviv-Yafo": ["特拉维夫"],
  },
  "IN": {
    "Bengaluru": ["班加罗尔", "班加羅爾"],
    "Chennai": ["金奈"],
    "Gurugram": ["古尔冈", "古爾岡"],
    "Hyderabad": ["海得拉巴"],
    "Lucknow": ["勒克瑙"],
    "Margao": ["马尔加奥"],
    "Mumbai": ["孟买"],
    "Pune": ["浦那"],
  },
  "IT": {
    "Alessandria": ["亚历山德里亚"],
    "Bologna": ["博洛尼亚"],
    "Brescia": ["布雷西亚"],
    "Caserta": ["卡塞塔"],
    "Florence": ["佛罗伦萨"],
    "Genoa": ["热那亚"],
    "Lucca": ["卢卡"],
    "Messina": ["墨西拿"],
    "Milan": ["米兰"],
    "Naples": ["那不勒斯"],
    "Padua": ["帕多瓦"],
    "Palermo": ["巴勒莫", "巴勒莫市"],
    "Pisa": ["比萨"],
    "Rome": ["罗马", "罗马市"],
    "Turin": ["都灵"],
    "Viareggio": ["维亚雷焦"],
  },
  "JP": {
    "Asahikawa": ["旭川市"],
    "Bunkyo City": ["文京区"],
    "Chiyoda City": ["千代田区"],
    "Fukuoka": ["福冈市", "福岡市"],
    "Gifu": ["岐阜市"],
    "Hakodate": ["函馆市", "函館市"],
    "Hamamatsu": ["滨松市"],
    "Hamura": ["羽村市"],
    "Hidaka": ["日高市"],
    "Higashiosaka": ["东大阪市"],
    "Himeji": ["姬路市"],
    "Hino": ["日野市"],
    "Hitachinaka": ["常陆那珂市"],
    "Iga": ["伊贺市"],
    "Inzai": ["印西市"],
    "Ise": ["伊势市", "伊勢市"],
    "Kagoshima": ["鹿儿岛市"],
    "Kamakura": ["镰仓市"],
    "Kashihara": ["橿原市"],
    "Kawagoe": ["川越市"],
    "Kimitsu": ["君津市"],
    "Kitakyushu": ["北九州市"],
    "Kobe": ["神户市"],
    "Kochi": ["高知市"],
    "Kofu": ["甲府市"],
    "Komaki": ["小牧市"],
    "Koriyama": ["郡山市"],
    "Koto City": ["江东区"],
    "Kumamoto": ["熊本市"],
    "Kurashiki": ["仓敷市", "倉敷市"],
    "Kure": ["吴市", "吳市"],
    "Kusatsu": ["草津町"],
    "Kyoto": ["京都市", "京都"],
    "Machida": ["町田市"],
    "Marugame": ["丸龟市", "丸龜市"],
    "Matsumoto": ["松本市"],
    "Matsuyama": ["松山市"],
    "Miyashiro": ["宫代町"],
    "Nagoya": ["名古屋市"],
    "Naha": ["那霸市"],
    "Noda": ["野田市"],
    "Oita": ["大分市"],
    "Ome": ["青梅市"],
    "Osaka": ["大阪市"],
    "Otaru": ["小樽市"],
    "Sakai": ["堺市"],
    "Sapporo": ["札幌市"],
    "Shimonoseki": ["下关市"],
    "Sōka": ["草加市"],
    "Takaoka": ["高冈市", "高岡市"],
    "Tawaramoto": ["田原本町"],
    "Tottori": ["鸟取市", "鳥取市"],
    "Toyama": ["富山市"],
    "Ube": ["宇部市"],
    "Ueda": ["上田市"],
    "Yamato": ["大和市"],
    "Yokkaichi": ["四日市市"],
    "Yokohama": ["横滨市"],
    "Yokosuka": ["横须贺市", "橫須賀市"],
  },
  "KR": {
    "Anyang": ["安养市"],
    "Busan": ["釜山广域市", "釜山", "釜山市"],
    "Daegu": ["大邱广域市", "大邱廣域市"],
    "Daejeon": ["大田广域市"],
    "Goyang-si": ["高阳市"],
    "Incheon": ["仁川广域市"],
    "Seongnam-si": ["城南市"],
    "Seoul": ["首尔特别市", "首尔"],
  },
  "KZ": {
    "Almaty": ["阿拉木图", "阿拉木圖"],
    "Temirtau 100000": ["铁米尔套"],
  },
  "LB": {
    "Beirut": ["贝鲁特"],
  },
  "LK": {
    "Colombo": ["可伦坡", "可倫坡"],
    "Galle": ["加勒"],
    "Kandy": ["康提"],
  },
  "LT": {
    "Kaunas": ["考纳斯", "考那斯"],
    "Klaipėda": ["克莱佩达"],
    "Vilnius": ["维尔纽斯"],
  },
  "LU": {
    "Luxembourg": ["卢森堡市", "盧森堡市"],
  },
  "LV": {
    "Riga": ["里加"],
  },
  "MD": {
    "Chișinău": ["基希讷乌"],
  },
  "MO": {
    "Macau": ["澳门"],
  },
  "MV": {
    "Malé": ["马累", "馬累", "瑪律", "玛律"],
  },
  "MX": {
    "Guadalajara": ["瓜达拉哈拉"],
    "Metepec": ["梅特佩克"],
    "Mexico City": ["墨西哥城"],
    "Monterrey": ["蒙特雷"],
    "Mérida": ["梅里达", "梅里達"],
    "Oaxaca": ["瓦哈卡市"],
    "Santiago de Querétaro": ["克雷塔罗"],
    "Tijuana": ["蒂华纳", "蒂華納"],
    "Toluca": ["托卢卡"],
  },
  "MY": {
    "Balik Pulau": ["浮罗山背"],
    "George Town": ["乔治市"],
    "Ipoh": ["怡保"],
    "Johor Bahru": ["新山"],
    "Klang": ["巴生市"],
    "Kota Kinabalu": ["亚庇"],
    "Kuala Lumpur": ["吉隆坡"],
    "Kuching": ["古晋", "古晉"],
    "Malacca": ["马六甲市", "马六甲"],
    "Petaling Jaya": ["八打灵再也"],
    "Shah Alam": ["莎阿南"],
  },
  "NL": {
    "Amsterdam": ["阿姆斯特丹"],
    "Deventer": ["代芬特尔"],
    "Dordrecht": ["多德雷赫特"],
    "Enschede": ["恩斯赫德"],
    "Leeuwarden": ["吕伐登"],
    "Rotterdam": ["鹿特丹"],
    "The Hague": ["海牙"],
    "Utrecht": ["乌得勒支"],
  },
  "NO": {
    "Fredrikstad": ["腓特烈斯塔"],
    "Oslo": ["奥斯陆"],
    "Stavanger": ["斯塔万格"],
  },
  "NP": {
    "Kathmandu 44600": ["加德满都"],
  },
  "NZ": {
    "Auckland": ["奥克兰", "奧克蘭都會區", "奥克兰都会区"],
    "Christchurch": ["基督城", "克赖斯特彻奇"],
    "Wellington": ["惠灵顿"],
  },
  "PA": {
    "Panama City": ["巴拿马城"],
  },
  "PE": {
    "Arequipa": ["阿雷基帕"],
    "Cusco": ["库斯科", "庫斯科"],
    "Jauja": ["豪哈"],
    "Lima District": ["利马区"],
    "Pucallpa": ["普卡尔帕", "普兰尔帕"],
    "San Vicente de Cañete": ["圣维森特德卡涅特"],
    "Trujillo": ["特鲁希略"],
  },
  "PH": {
    "Baguio": ["碧瑶市"],
    "Cebu City": ["宿雾市"],
    "Manila": ["马尼拉", "馬尼拉"],
    "Quezon City": ["奎松市"],
    "Taguig": ["塔吉格"],
  },
  "PL": {
    "Gdańsk": ["格但斯克"],
    "Gdynia": ["格丁尼亚"],
    "Sokolka": ["索库乌卡", "索庫烏卡"],
    "Sopot": ["索波特"],
    "Szczecin": ["什切青"],
    "Warsaw": ["华沙", "華沙"],
    "Wrocław": ["弗罗茨瓦夫"],
  },
  "PT": {
    "Aveiro": ["阿威罗"],
    "Cascais": ["卡斯凯什"],
    "Covilha": ["科维良"],
    "Evora": ["埃武拉"],
    "Faro": ["法鲁"],
    "Lisbon": ["里斯本"],
    "Porto": ["波尔图"],
  },
  "PY": {
    "Asunción": ["亚松森", "亞松森"],
  },
  "RO": {
    "Bucharest": ["布加勒斯特"],
    "Constanța": ["康斯坦察"],
    "Timișoara": ["蒂米什瓦拉"],
  },
  "RS": {
    "Belgrade": ["贝尔格莱德"],
    "Niš": ["尼什"],
  },
  "RU": {
    "Kaliningrad": ["加里宁格勒", "加里寧格勒"],
    "Kazan": ["喀山"],
    "Moscow": ["莫斯科"],
    "Nizhny Novgorod": ["下诺夫哥罗德"],
    "Novosibirsk": ["新西伯利亚"],
    "St Petersburg": ["圣彼得堡", "聖彼得堡"],
  },
  "SE": {
    "Gothenburg": ["哥德堡"],
    "Lund": ["隆德"],
    "Malmö": ["马尔默", "马尔莫"],
    "Stockholm": ["斯德哥尔摩"],
  },
  "SG": {
    "Singapore": ["新加坡"],
  },
  "SI": {
    "Ljubljana": ["卢布尔雅那"],
  },
  "SK": {
    "Bratislava": ["布拉迪斯拉发"],
  },
  "TH": {
    "Bangkok": ["曼谷"],
    "Chiang Mai": ["清迈", "清邁"],
  },
  "TR": {
    "İstanbul": ["伊斯坦堡", "伊斯坦布尔"],
    "İzmir": ["伊兹密尔"],
  },
  "TW": {
    "Beitun District": ["北屯区"],
    "台中市": ["台中市"],
    "台北市": ["台北市"],
    "台南市": ["台南市"],
    "嘉義縣": ["嘉义县"],
    "屏東縣": ["屏东县"],
    "新北市": ["新北市"],
    "桃園市": ["桃园市"],
    "澎湖縣": ["澎湖县"],
    "花蓮縣": ["花莲县"],
    "高雄市": ["高雄市"],
  },
  "UA": {
    "Dnipro": ["第聂伯罗", "聶伯城", "聂伯城"],
    "Kharkiv": ["哈尔科夫"],
    "Kyiv": ["基辅"],
    "Lviv": ["利沃夫"],
    "Mykolaiv": ["尼古拉耶夫"],
    "Odesa": ["敖德萨", "敖德薩"],
  },
  "US": {
    "Albany": ["奥尔巴尼"],
    "Albuquerque": ["阿布奎基"],
    "Alexandria": ["亚历山德里亚"],
    "Altamont": ["阿尔塔蒙特"],
    "Ames": ["埃姆斯", "艾姆斯"],
    "Ann Arbor": ["安娜堡"],
    "Annapolis": ["安纳波利斯", "安那波利斯"],
    "Appleton": ["阿普尔顿"],
    "Arlington": ["阿灵顿"],
    "Atlanta": ["亚特兰大"],
    "Augusta": ["奥古斯塔"],
    "Austin": ["奥斯汀", "奧斯汀"],
    "Bentonville": ["本顿维", "本頓維"],
    "Berkeley": ["伯克利"],
    "Birmingham": ["伯明翰"],
    "Bloomington": ["布卢明顿"],
    "Boise": ["博伊西"],
    "Boston": ["波士顿"],
    "Boulder": ["博尔德", "波德"],
    "Buellton": ["比尔顿"],
    "Buffalo": ["水牛城"],
    "Burlington": ["伯灵顿", "伯靈頓"],
    "Champaign": ["尚佩恩"],
    "Charleston": ["查尔斯顿"],
    "Charlotte": ["夏洛特"],
    "Chattanooga": ["查塔努加"],
    "Cheyenne": ["夏延"],
    "Chicago": ["芝加哥"],
    "Columbus": ["哥伦布"],
    "Dallas": ["达拉斯", "達拉斯"],
    "Dayton": ["代顿"],
    "Denver": ["丹佛"],
    "Evanston": ["埃文斯顿"],
    "Fairbanks": ["费尔班克斯", "費爾班克斯"],
    "Fayetteville": ["费耶特维尔"],
    "Flagstaff": ["弗拉格斯塔夫"],
    "Fort Lauderdale": ["劳德代尔堡"],
    "Fort Oglethorpe": ["奥格尔索普堡"],
    "Fort Smith": ["史密斯堡"],
    "Fort Wayne": ["韦恩堡", "韋恩堡"],
    "Frederick": ["弗雷德里克"],
    "Fredericksburg": ["弗雷德里克斯堡"],
    "Fresno": ["弗雷斯诺"],
    "Frisco": ["弗里斯科"],
    "Gainesville": ["盖恩斯维尔", "蓋恩斯維爾"],
    "Gilbert": ["吉尔伯特"],
    "Grand Island": ["格兰德艾兰", "格蘭德艾蘭"],
    "Grand Rapids": ["大急流城"],
    "Honolulu": ["檀香山"],
    "Houston": ["休斯敦", "休斯顿"],
    "Huntsville": ["亨茨维尔"],
    "Indianapolis": ["印第安纳波利斯", "印第安納波利斯"],
    "Irvine": ["尔湾", "爾灣", "歐文", "欧文"],
    "Jacksonville": ["杰克逊维尔"],
    "Jacksonville Beach": ["杰克逊维尔海滩"],
    "Jersey City": ["泽西市"],
    "Kansas City": ["堪萨斯城", "堪薩斯城"],
    "Knoxville": ["诺克斯维尔", "諾克斯維爾"],
    "Laguna Beach": ["拉古纳比奇", "拉古纳海滩"],
    "Las Vegas": ["拉斯维加斯"],
    "Little Rock": ["小岩城"],
    "Longmont": ["朗蒙特"],
    "Los Angeles": ["洛杉矶"],
    "Madison": ["麦迪逊"],
    "Manhattan": ["曼哈顿", "曼哈頓"],
    "Marfa": ["马尔法"],
    "Miami": ["迈阿密"],
    "Minneapolis": ["明尼阿波利斯"],
    "Mobile": ["莫比尔"],
    "Morristown": ["莫里斯敦"],
    "Muncie": ["曼西"],
    "Murrieta": ["穆列塔"],
    "Nampa": ["楠帕"],
    "Naperville": ["内珀维尔", "內珀維爾"],
    "Nashville": ["纳什维尔"],
    "New Haven": ["纽黑文"],
    "New Orleans": ["新奥尔良"],
    "New York": ["纽约", "紐約市", "纽约市", "紐約"],
    "Oakland": ["奥克兰"],
    "Oklahoma City": ["奥克拉荷马市", "奧克拉荷馬市"],
    "Olathe": ["奥拉西", "奧拉西"],
    "Olympia": ["奥林匹亚", "奧林匹亞"],
    "Orlando": ["奥兰多"],
    "Palm Springs": ["棕榈泉", "棕櫚泉"],
    "Paradise": ["天堂市"],
    "Petaluma": ["佩塔卢马"],
    "Philadelphia": ["费城", "費城"],
    "Phoenix": ["凤凰城", "鳳凰城"],
    "Pittsburgh": ["匹兹堡"],
    "Portland": ["波特兰", "波特蘭"],
    "Princeton": ["普林斯顿"],
    "Providence": ["普罗维登斯"],
    "Provo": ["普罗沃", "普若佛"],
    "Richmond": ["里士满"],
    "Riverside": ["里弗赛德"],
    "Rochester": ["罗彻斯特", "羅徹斯特"],
    "Sacramento": ["沙加缅度", "沙加緬度"],
    "Salem": ["塞勒姆"],
    "Salt Lake City": ["盐湖城"],
    "San Antonio": ["圣安东尼奥"],
    "San Diego": ["圣地牙哥", "聖地牙哥"],
    "San Francisco": ["旧金山"],
    "San Jose": ["圣荷西", "聖荷西"],
    "Santa Barbara": ["圣巴巴拉"],
    "Saratoga Springs": ["萨拉托加泉", "萨拉托加温泉市", "薩拉托加溫泉市"],
    "Savannah": ["萨凡纳", "薩凡納"],
    "Schenectady": ["斯克内克塔迪"],
    "Scottsdale": ["斯科茨代尔", "斯科茨代爾"],
    "Seattle": ["西雅图", "西雅圖"],
    "Shreveport": ["什里夫波特"],
    "Springfield": ["斯普林菲尔德"],
    "St. George": ["圣乔治"],
    "St. Louis": ["圣路易斯"],
    "Stamford": ["斯坦福"],
    "Tacoma": ["塔科马"],
    "Tallahassee": ["塔拉赫西"],
    "Tampa": ["坦帕"],
    "Temecula": ["特曼库拉"],
    "Tucson": ["图森"],
    "Tulsa": ["塔尔萨"],
    "Tuscaloosa": ["塔斯卡卢萨"],
    "Urbandale": ["厄班代尔"],
    "Washington": ["华盛顿哥伦比亚特区", "华盛顿特区"],
    "Waukesha": ["沃基肖"],
    "Youngstown": ["扬斯敦"],
  },
  "UY": {
    "Colonia del Sacramento": ["科洛尼亚-德尔萨克拉门托", "科洛尼亞·德爾·沙加緬度", "科洛尼亚·德尔·沙加缅度"],
    "Montevideo": ["蒙得维的亚", "蒙特維多", "蒙特维多"],
  },
  "VN": {
    "Ho Chi Minh City": ["胡志明市"],
  },
  "ZA": {
    "Cape Town": ["开普敦", "開普敦"],
    "Johannesburg": ["约翰内斯堡"],
    "Pietermaritzburg": ["彼得马里茨堡"],
    "Pretoria": ["比勒陀利亚", "比勒陀利亞"],
  },
};
